# Generated by Django 4.2.10 on 2024-05-24 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion", "0005_alter_follow_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="notion",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_notions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="notion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="notion.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="notion",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="notions", to="notion.hashtag"
            ),
        ),
    ]
