# Generated by Django 4.2.10 on 2024-05-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0008_notion_custom_group"),
    ]

    operations = [
        migrations.RemoveField(model_name="notion", name="custom_group",),
    ]
