# Generated by Django 4.2.10 on 2024-05-27 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion", "0010_alter_comment_content_alter_notion_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notion_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
