# Generated by Django 4.2.10 on 2024-05-28 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0011_hashtag_media_media_type_media_hashtags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion", "0015_remove_notification_related_media_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_notifications",
                to="notion.comment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_notifications",
                to="user_profile.media",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("follow", "Follow"),
                    ("like", "Like"),
                    ("comment", "Comment"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
