# Generated by Django 4.2.10 on 2024-07-01 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0017_delete_comment"),
        ("notion", "0016_notification_related_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="media",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="user_profile.media",
            ),
        ),
    ]
