# Generated by Django 4.2.10 on 2024-07-23 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0033_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 22, 12, 41, 10, 821043, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
