# Generated by Django 4.2.10 on 2024-07-25 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0036_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 24, 7, 13, 30, 217054, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
