# Generated by Django 4.2.10 on 2024-08-02 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0040_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 1, 12, 39, 46, 106181, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
