# Generated by Django 4.2.10 on 2024-08-10 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0048_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 9, 7, 55, 7, 852707, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
