# Generated by Django 4.2.10 on 2024-08-11 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0049_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 10, 14, 41, 25, 54198, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
