# Generated by Django 4.2.10 on 2024-08-12 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0052_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 11, 17, 47, 44, 391402, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
