# Generated by Django 4.2.10 on 2024-08-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0056_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 22, 17, 2, 39, 383988, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
