# Generated by Django 4.2.10 on 2024-08-24 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0061_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 23, 4, 42, 20, 770988, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
