# Generated by Django 4.2.10 on 2024-08-29 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0065_alter_notion_deletion_date_blockeduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 28, 15, 30, 9, 224700, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
