# Generated by Django 4.2.10 on 2024-09-10 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0078_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 10, 8, 35, 11, 173568, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
