# Generated by Django 4.2.10 on 2024-09-14 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0081_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 23, 12, 13, 14, 26809, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
