# Generated by Django 4.2.10 on 2024-09-15 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion", "0084_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="notion",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_notions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="Like",),
    ]
