CATEGORY_CHOICES = [
    ('media_journalism', 'Media and Journalism'),
    ('entertainment', 'Entertainment'),
    ('sports_fitness', 'Sports and Fitness'),
    ('creators_influencers', 'Creators and Influencers'),
    ('education_learning', 'Education and Learning'),
    ('business_entrepreneurship', 'Business and Entrepreneurship'),
    ('art_design', 'Art and Design'),
    ('social_causes', 'Social Causes and Activism'),
    ('tech_science', 'Technology and Science'),
    ('health_wellness', 'Health and Wellness'),
    ('hobbies_interests', 'Hobbies and Interests'),
    ('government_politics', 'Government and Politics'),
    ('religious_spiritual', 'Religious and Spiritual'),
    ('travel_adventure', 'Travel and Adventure'),
    ('comedy_memes', 'Comedy and Memes'),
    ('gaming', 'Gaming'),
    ('finance', 'Finance'),
]
