# Generated by Django 4.2.10 on 2024-05-23 19:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion", "0004_alter_follow_follower_alter_follow_following_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow", unique_together={("follower", "following", "created_at")},
        ),
    ]
