# Generated by Django 4.2.10 on 2024-05-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0045_remove_userupload_upload_source_and_more"),
        ("notion", "0007_notification_comment_notification_liked_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notion",
            name="custom_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notions",
                to="only_card.customgroup",
            ),
        ),
    ]
