# Generated by Django 4.2.10 on 2024-05-27 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion", "0012_remove_notification_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="related_media",),
        migrations.RemoveField(model_name="notification", name="related_user",),
        migrations.RemoveField(model_name="notification", name="type",),
        migrations.AddField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="notion.comment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="liked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="notion.notion",
            ),
        ),
    ]
