# Generated by Django 4.2.10 on 2024-07-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0017_comment_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="notion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="notion.notion",
            ),
        ),
    ]
