# Generated by Django 4.2.10 on 2024-07-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0018_alter_comment_notion"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_notion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_notifications",
                to="notion.notion",
            ),
        ),
    ]
