# Generated by Django 4.2.10 on 2024-07-03 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion", "0019_notification_related_notion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow", unique_together={("follower", "following")},
        ),
    ]
