# Generated by Django 4.2.10 on 2024-07-04 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0021_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 3, 18, 47, 20, 90455, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
