# Generated by Django 4.2.10 on 2024-07-05 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0023_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 4, 12, 57, 34, 578983, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
