# Generated by Django 4.2.10 on 2024-07-24 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0034_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 23, 9, 1, 51, 899904, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
