# Generated by Django 4.2.10 on 2024-07-25 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0038_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 24, 10, 4, 43, 31075, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
