# Generated by Django 4.2.10 on 2024-08-17 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0054_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 16, 8, 7, 18, 75611, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
