# Generated by Django 4.2.10 on 2024-08-25 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0063_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 24, 6, 29, 12, 637864, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
