# Generated by Django 4.2.10 on 2024-09-15 08:44

from django.db import migrations, models
import notion.models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0083_alter_notion_deletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="deletion_date",
            field=models.DateTimeField(
                db_index=True, default=notion.models.get_deletion_date
            ),
        ),
    ]
