# Generated by Django 4.2.16 on 2024-10-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0086_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
