# Generated by Django 4.2.16 on 2025-02-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0042_media_category_media_country_media_is_story_and_more'),
        ('notion', '0087_remove_comment_dislikes_remove_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_profile.audio'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to='user_profile.audio'),
        ),
    ]
