# Generated by Django 4.2.10 on 2024-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0002_userupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="document_type",
            field=models.CharField(default="Aadhar Card", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userupload",
            name="file",
            field=models.FileField(default="Aadhar Card", upload_to="uploads/"),
        ),
    ]
