# Generated by Django 4.2.10 on 2024-04-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0007_card_file_serviceproviderregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceproviderregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
