# Generated by Django 4.2.10 on 2024-04-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0015_kyc"),
    ]

    operations = [
        migrations.RemoveField(model_name="card", name="card_type",),
        migrations.AddField(
            model_name="kyc",
            name="uploaded_image",
            field=models.ImageField(null=True, upload_to="kyc_images/"),
        ),
        migrations.AlterField(
            model_name="card",
            name="card_number",
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="kyc_video",
            field=models.FileField(upload_to="kyc_videos/"),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
