# Generated by Django 4.2.10 on 2024-05-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0021_alter_customgroup_pending_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customgroup",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
