# Generated by Django 4.2.10 on 2024-05-04 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0022_customgroup_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="customgroup",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="admin_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
