# Generated by Django 4.2.10 on 2024-05-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0029_registrationform_subgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userassociation",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="only_card.customgroup",
            ),
        ),
    ]
