# Generated by Django 4.2.10 on 2024-05-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0031_rename_userprofile_profilepicture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilepicture", old_name="profile_picture", new_name="image",
        ),
    ]
