# Generated by Django 4.2.10 on 2024-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0034_notion_comments_notion_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="notion", name="comments",),
        migrations.RemoveField(model_name="notion", name="likes",),
    ]
