# Generated by Django 4.2.10 on 2024-05-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0037_alter_notion_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notion", old_name="created_by", new_name="user",
        ),
    ]
