# Generated by Django 4.2.10 on 2024-05-20 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0040_alter_card_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notion",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="only_card_notion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
