# Generated by Django 4.2.10 on 2024-05-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0044_userupload_upload_source_alter_userupload_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userupload", name="upload_source",),
        migrations.AlterField(
            model_name="userupload",
            name="file",
            field=models.FileField(default="Aadhar Card", upload_to="uploads/"),
        ),
    ]
