# Generated by Django 4.2.10 on 2024-08-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0045_remove_userupload_upload_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userupload", name="file",),
        migrations.CreateModel(
            name="UserUploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="only_card.userupload",
                    ),
                ),
            ],
        ),
    ]
