# Generated by Django 4.2.10 on 2024-08-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0046_remove_userupload_file_useruploadfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="file",
            field=models.FileField(default="Aadhar Card", upload_to="uploads/"),
        ),
        migrations.DeleteModel(name="UserUploadFile",),
    ]
