# Generated by Django 4.2.10 on 2024-08-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0047_userupload_file_delete_useruploadfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userupload",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
