# Generated by Django 4.2.10 on 2024-08-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0049_userupload_encryption_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userupload",
            name="encryption_key",
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
