# Generated by Django 4.2.10 on 2024-10-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0053_delete_temporarilylock"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("token", models.CharField(max_length=100, unique=True)),
                ("token_expires", models.DateTimeField()),
            ],
        ),
    ]
