# Generated by Django 4.2.16 on 2025-03-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('previous', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('nonce', models.IntegerField()),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
    ]
