# Generated by Django 4.2.10 on 2024-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmk_chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block", name="hash", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="block", name="previous", field=models.CharField(max_length=64),
        ),
    ]
