# Generated by Django 4.2.10 on 2024-05-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0005_profile_bio_profile_cover_photo_alter_media_file_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(name="Notification",),
    ]
