# Generated by Django 4.2.10 on 2024-06-06 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0011_hashtag_media_media_type_media_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_in_media", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
