# Generated by Django 4.2.10 on 2024-06-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0015_ad"),
    ]

    operations = [
        migrations.DeleteModel(name="Ad",),
    ]
