# Generated by Django 4.2.10 on 2024-07-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0019_alter_engagement_engagement_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="report_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="media",
            name="reported_by",
            field=models.ManyToManyField(
                blank=True, related_name="reported_media", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.media",
                    ),
                ),
            ],
        ),
    ]
