# Generated by Django 4.2.10 on 2024-07-25 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0020_media_report_count_media_reported_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media", old_name="created_at", new_name="upload_time",
        ),
        migrations.AddField(
            model_name="media",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserHashtagPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_hashtags", models.JSONField(default=list)),
                ("not_interested_hashtags", models.JSONField(default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
