# Generated by Django 4.2.10 on 2024-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0022_rename_upload_time_media_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
