# Generated by Django 4.2.10 on 2024-08-11 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0027_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="viewers",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_stories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
