# Generated by Django 4.2.10 on 2024-08-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0028_story_viewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhashtagpreference",
            name="viewed_media",
            field=models.JSONField(default=list),
        ),
    ]
