# Generated by Django 4.2.10 on 2024-08-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0030_profile_is_private"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="is_private",),
    ]
