# Generated by Django 4.2.10 on 2024-08-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0032_profile_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
