# Generated by Django 4.2.10 on 2024-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0034_buddy"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhashtagpreference",
            name="not_interested_media",
            field=models.JSONField(default=list),
        ),
    ]
