# Generated by Django 4.2.10 on 2024-10-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0038_interaction_interaction_unique_interaction"),
    ]

    operations = [
        migrations.DeleteModel(name="Interaction",),
    ]
