# Generated by Django 4.2.10 on 2024-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0003_userupload_document_type_userupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
