# Generated by Django 4.2.10 on 2024-04-17 08:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0005_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="country",
            field=django_countries.fields.CountryField(default="INDIA", max_length=2),
            preserve_default=False,
        ),
    ]
