# Generated by Django 4.2.10 on 2024-04-20 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0008_serviceproviderregistration_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceProviderRegistration", new_name="registration_form",
        ),
    ]
