# Generated by Django 4.2.10 on 2024-04-21 12:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0010_alter_registration_form_legal_documents"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="registration_form", new_name="RegistrationForm",
        ),
    ]
