# Generated by Django 4.2.10 on 2024-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0011_rename_registration_form_registrationform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationform",
            name="legal_documents",
            field=models.FileField(blank=True, null=True, upload_to="legal_documents/"),
        ),
    ]
