# Generated by Django 4.2.10 on 2024-04-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0013_remove_card_description_remove_card_image_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="card", old_name="user_id", new_name="user",),
    ]
