# Generated by Django 4.2.10 on 2024-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0019_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customgroup",
            name="pending_approval",
            field=models.CharField(
                choices=[("approve", "Approve"), ("deny", "Deny")],
                default="approve",
                max_length=10,
            ),
        ),
    ]
