# Generated by Django 4.2.10 on 2024-05-03 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0020_customgroup_pending_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgroup",
            name="pending_approval",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("deny", "Deny"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customgroup",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="custom_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
