# Generated by Django 4.2.10 on 2024-05-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0023_customgroup_admins"),
    ]

    operations = [
        migrations.RemoveField(model_name="customgroup", name="admins",),
    ]
