# Generated by Django 4.2.10 on 2024-05-13 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0030_alter_userassociation_subgroup"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserProfile", new_name="ProfilePicture",),
    ]
