# Generated by Django 4.2.10 on 2024-05-13 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0033_rename_profilepicture_userprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notion", name="comments", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notion",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="notion_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
