# Generated by Django 4.2.10 on 2024-05-14 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_card", "0039_alter_card_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
