# Generated by Django 4.2.10 on 2024-05-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0042_delete_notion"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
