# Generated by Django 4.2.10 on 2024-05-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0043_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="upload_source",
            field=models.CharField(
                choices=[
                    ("landing_page", "Landing Page"),
                    ("subgroup_landing_page", "Subgroup Landing Page"),
                ],
                default="landing_page",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userupload",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
        migrations.DeleteModel(name="ImageUpload",),
    ]
