# Generated by Django 4.2.10 on 2024-08-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0048_alter_userupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="encryption_key",
            field=models.CharField(max_length=44, null=True),
        ),
    ]
