# Generated by Django 4.2.10 on 2024-09-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("only_card", "0052_lockedfield_temporarilylock"),
    ]

    operations = [
        migrations.DeleteModel(name="TemporarilyLock",),
    ]
