# Generated by Django 4.2.16 on 2025-02-23 11:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('only_card', '0054_temporaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userupload',
            name='user_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='only_card.userstorage'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
