# Generated by Django 4.2.10 on 2024-05-22 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0003_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_uploads", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="Upload",),
    ]
