# Generated by Django 4.2.10 on 2024-05-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0006_delete_notification"),
    ]

    operations = [
        migrations.DeleteModel(name="Follow",),
    ]
