# Generated by Django 4.2.10 on 2024-05-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0009_alter_media_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="media", name="hashtags",),
        migrations.RemoveField(model_name="media", name="media_type",),
        migrations.DeleteModel(name="Hashtag",),
    ]
