# Generated by Django 4.2.10 on 2024-06-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0012_media_caption_media_tagged_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="media", name="description",),
    ]
