# Generated by Django 4.2.10 on 2024-07-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0018_media_view_count_engagement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="engagement_type",
            field=models.CharField(
                choices=[("view", "View"), ("like", "Like"), ("comment", "Comment")],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="engagement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("engagement_type", "view")),
                fields=("media", "user", "engagement_type"),
                name="unique_view",
            ),
        ),
    ]
