# Generated by Django 4.2.10 on 2024-07-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0021_rename_created_at_media_upload_time_media_is_paid_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="media", old_name="upload_time", new_name="created_at",
        ),
    ]
