# Generated by Django 4.2.10 on 2024-08-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0023_alter_hashtag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhashtagpreference",
            name="viewed_hashtags",
            field=models.JSONField(default=list),
        ),
    ]
