# Generated by Django 4.2.10 on 2024-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0024_userhashtagpreference_viewed_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_uploads",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by_users", to="user_profile.media"
            ),
        ),
    ]
