# Generated by Django 4.2.10 on 2024-08-09 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0025_profile_saved_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_media", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
