# Generated by Django 4.2.10 on 2024-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0029_userhashtagpreference_viewed_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
