# Generated by Django 4.2.10 on 2024-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0035_userhashtagpreference_not_interested_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
