# Generated by Django 4.2.10 on 2024-10-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0036_profile_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
