# Generated by Django 4.2.10 on 2024-10-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0039_delete_interaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhashtagpreference",
            name="search_hashtags",
            field=models.JSONField(default=list),
        ),
    ]
