# Generated by Django 4.2.16 on 2025-02-23 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import service_auth.user_profile.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0041_alter_userhashtagpreference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the media.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='is_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, help_text='Select the category that best describes your content.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userhashtagpreference',
            name='liked_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.media'),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=service_auth.user_profile.storage.CompressedMediaStorage(), upload_to='media/')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='Category of the audio.', max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('duration', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)])),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(104857600)])),
                ('hashtags', models.ManyToManyField(blank=True, related_name='audio', to='user_profile.hashtag')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_audio', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ManyToManyField(blank=True, related_name='reported_audio', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_audio', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
