# Generated by Django 4.2.16 on 2025-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0043_media_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
