# Generated by Django 4.2.16 on 2025-06-08 06:11

from django.db import migrations, models
import service_auth.user_profile.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0044_media_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(storage=service_auth.user_profile.storage.CompressedMediaStorage(), upload_to='media/audio'),
        ),
    ]
