# Generated by Django 4.2.10 on 2024-07-20 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("only_message", "0003_userencryptionkeys"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userencryptionkeys",
            old_name="private_key",
            new_name="encryption_private_key",
        ),
        migrations.RenameField(
            model_name="userencryptionkeys",
            old_name="public_key",
            new_name="encryption_public_key",
        ),
        migrations.AddField(
            model_name="message", name="signature", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userencryptionkeys",
            name="signing_private_key",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userencryptionkeys",
            name="signing_public_key",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="ConversationKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField()),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
