# Generated by Django 4.2.10 on 2024-07-25 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "only_message",
            "0004_rename_private_key_userencryptionkeys_encryption_private_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedinuser",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
