# Generated by Django 4.2.10 on 2024-09-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_message", "0005_loggedinuser_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="messages/files/"),
        ),
    ]
