# Generated by Django 4.2.10 on 2024-09-27 12:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("only_message", "0006_message_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/path/to/save/uploads"
                ),
                upload_to="messages/files/",
            ),
        ),
    ]
